name: build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Clean build folders
        shell: pwsh
        run: |
          if (Test-Path build) { Remove-Item build -Recurse -Force }
          if (Test-Path dist) { Remove-Item dist -Recurse -Force }

      - name: Build Windows exe
        run: |
          pyinstaller --noconfirm --clean SportSchedule.spec

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v5
        with:
          name: SportSchedule-windows
          path: dist/SportSchedule.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Clean build folders
        run: |
          rm -rf build dist

      - name: Build macOS app
        run: |
          pyinstaller --noconfirm --clean SportSchedule-macos.spec

      - name: Zip macOS app
        run: |
          cd dist
          zip -r SportSchedule-macos.zip SportSchedule.app

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v5
        with:
          name: SportSchedule-macos
          path: dist/SportSchedule-macos.zip
